apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nagendrappa1/jenkins:latest   # or use ${IMAGE_TAG} if versioned
        ports:
        - containerPort: 80
