apiVersion: apps/v1
kind : Namespace
metadata:
  name: dev
  labels:
    app: webapp
spec:
  containers: 
    - name: webapp-pod
      image: nagendrappa1/jenkins
      ports: 
        - containerPort: 80
        

  







